### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by codedragon** [HasBob/echo_sockets#1]
Unfortunately, I can't write in-line in your code, so I'll just make some comments here.

http_server:
you only need to do the sock.listen once, so put it outside of your loop

echo_client:
better to assign 16 to a variable, since you use it in more than one place.
You are sending to sys.stderr in your last print statement, instead of log_buffer, which may or may not be sys.stderr, depending on how the client is called.

Minor points, good job!

**Comment by HasBob** [comment]
Thanks! I'll add you two to repos going forward.
